apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "15"
    field.cattle.io/creatorId: user-27tn4
    field.cattle.io/publicEndpoints: '[{"addresses":["10.22.0.121"],"port":30081,"protocol":"TCP","serviceName":"default:studygolang-app-nodeport","allNodes":true}]'
  creationTimestamp: "2020-01-22T08:57:31Z"
  generation: 28
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-studygolang-app
  name: studygolang-app
  namespace: default
  resourceVersion: "14279920"
  selfLink: /apis/apps/v1/namespaces/default/deployments/studygolang-app
  uid: 49432355-490c-476a-9c7f-6fb99f2842f9
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-studygolang-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-01-23T05:14:23Z"
        field.cattle.io/ports: '[[{"containerPort":1323,"dnsName":"studygolang-app-nodeport","hostPort":0,"kind":"NodePort","name":"1323tcp300811","protocol":"TCP","sourcePort":30081}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-studygolang-app
    spec:
      containers:
      - args:
        - go
        - run
        - main.go
        image: kataruonosato/studygolang:app
        imagePullPolicy: Always
        name: studygolang-app
        ports:
        - containerPort: 1323
          name: 1323tcp300811
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-01-23T05:14:22Z"
    lastUpdateTime: "2020-01-23T05:14:32Z"
    message: ReplicaSet "studygolang-app-996d5d5c4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-01-23T10:28:43Z"
    lastUpdateTime: "2020-01-23T10:28:43Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 28
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

